# sequence: "03"
# output_folder: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/LidarMOS/03"
# scans_path: "/home/joseph/catkin/git/LiDAR-MOS/data/sequences/03/clean_scans"
# calib_path: "/home/joseph/catkin/git/LiDAR-MOS/data/sequences/03/calib.txt"
# pose_path: "/home/joseph/catkin/git/LiDAR-MOS/data/sequences/03/poses.txt"
# voxel: 0.2
# removal_thresh: 2.7

# sequence: "04"
# output_folder: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/LidarMOS/04"
# scans_path: "/home/joseph/catkin/git/LiDAR-MOS/data/sequences/04/clean_scans"
# calib_path: "/home/joseph/catkin/git/LiDAR-MOS/data/sequences/04/calib.txt"
# pose_path: "/home/joseph/catkin/git/LiDAR-MOS/data/sequences/04/poses.txt"
# voxel: 0.2
# removal_thresh: 2.7

sequence: "08"
output_folder: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/LidarMOS/08"
scans_path: "/home/joseph/catkin/git/LiDAR-MOS/data/sequences/08/clean_scans"
calib_path: "/home/joseph/catkin/git/LiDAR-MOS/data/sequences/08/calib.txt"
pose_path: "/home/joseph/catkin/git/LiDAR-MOS/data/sequences/08/poses.txt"
voxel: 0.2
removal_thresh: 2.7
skip: 5
