# sequence: "04"
# output_folder: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/object_detect_results/04/rcnn/"
# scans_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/object_detect_results/04/rcnn/projected"
# calib_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/sequences/04/calib.txt"
# pose_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/sequences/04/poses.txt"
# voxel: 0.2
# removal_thresh: 2.7


# sequence: "04"
# output_folder: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/NoMorePotentiallyDynamicObjects/04/pointpillars/0.3/"
# scans_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/NoMorePotentiallyDynamicObjects/04/pointpillars/0.3/projected"
# calib_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/sequences/04/calib.txt"
# pose_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/sequences/04/poses.txt"
# voxel: 0.2
# removal_thresh: 2.7

# sequence: "04"
# output_folder: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/NoMorePotentiallyDynamicObjects/04/pointpillars/0.5/"
# scans_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/NoMorePotentiallyDynamicObjects/04/pointpillars/0.5/projected"
# calib_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/sequences/04/calib.txt"
# pose_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/sequences/04/poses.txt"
# voxel: 0.2
# removal_thresh: 2.7

# sequence: "04"
# output_folder: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/NoMorePotentiallyDynamicObjects/04/rcnn/0.3/"
# scans_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/NoMorePotentiallyDynamicObjects/04/rcnn/0.3/projected"
# calib_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/sequences/04/calib.txt"
# pose_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/sequences/04/poses.txt"
# voxel: 0.2
# removal_thresh: 2.7

sequence: "04"
output_folder: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/NoMorePotentiallyDynamicObjects/04/rcnn/0.5/"
scans_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/results/NoMorePotentiallyDynamicObjects/04/rcnn/0.5/projected"
calib_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/sequences/04/calib.txt"
pose_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/sequences/04/poses.txt"
voxel: 0.2
removal_thresh: 2.7