#filters: ["moving", "vehicles"]
filters: ["moving"]
start_idx: 0
end_idx: 50
#skip: 1
sequence: "01"
data_path: "/media/joseph/7E408025407FE1F7/Datasets/Kitti/odometry/dataset/sequences/"
removal_thresh: 3